"""Tools the Tester can write on the spot.

Every tool follows one contract so the Tester can run any of them the same way:

    python <tool>.py <pytest node id> <runs>
    -> prints one JSON line: {"test", "runs", "failures", "failure_rate", "failing": [...]}

Offline the Tester instantiates a template matched to the suspected source of
flakiness; with an LLM it asks the model to write the harness against the same
contract. Either way the tool is validated before it is trusted.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

from .llm import LLM, LLMError

log = logging.getLogger("swarm.tester")

CONTRACT = (
    "A standalone Python 3 script. Usage: python tool.py <pytest node id> <runs>. It runs the test <runs> times "
    "in fresh subprocesses (sys.executable -m pytest -q -p no:cacheprovider <node id>) and prints exactly one JSON "
    'line: {"test": str, "runs": int, "failures": int, "failure_rate": float, "failing": [labels of failing runs]}. '
    "Standard library only, no network access."
)

_TEMPLATE = '''#!/usr/bin/env python3
"""{description}

Generated by the swarm's Tester agent for {task_id}.
Usage: python {tool_id}.py <pytest node id> [runs]
"""
import json
import os
import subprocess
import sys


def run_once(test, label, extra_env):
    env = dict(os.environ)
    env.update(extra_env)
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", test],
        env=env, capture_output=True, text=True, timeout=60,
    )
    return {{"label": label, "passed": proc.returncode == 0}}


def main():
    test = sys.argv[1]
    runs = int(sys.argv[2]) if len(sys.argv) > 2 else {default_runs}
    results = []
    for i in range(runs):
{loop_body}
    failing = [r["label"] for r in results if not r["passed"]]
    print(json.dumps({{
        "test": test, "runs": runs, "failures": len(failing),
        "failure_rate": round(len(failing) / runs, 3), "failing": failing,
    }}))


if __name__ == "__main__":
    main()
'''

KINDS = {
    "hash-order": dict(
        stem="hashseed_sweep",
        description="Runs one pytest test repeatedly under different PYTHONHASHSEED values to expose "
                    "ordering flakiness from set/dict iteration order (hash randomization).",
        tags=["flaky", "hash", "ordering", "set", "pythonhashseed", "repeat", "harness"],
        loop_body='        results.append(run_once(test, "PYTHONHASHSEED=%d" % i, {"PYTHONHASHSEED": str(i)}))',
    ),
    "rng": dict(
        stem="repeat_run",
        description="Runs one pytest test many times in fresh processes with unseeded randomness to measure "
                    "the failure rate of randomness-driven (RNG / jitter) flakiness.",
        tags=["flaky", "random", "rng", "jitter", "repeat", "harness", "failure rate"],
        loop_body='        results.append(run_once(test, "run %d" % i, {"PYTHONHASHSEED": "random"}))',
    ),
    "time": dict(
        stem="timing_stress",
        description="Runs one pytest test repeatedly in fresh processes to measure timing-dependent flakiness "
                    "(sleeps, clocks, timeouts).",
        tags=["flaky", "timing", "time", "sleep", "clock", "repeat", "harness"],
        loop_body='        results.append(run_once(test, "run %d" % i, {}))',
    ),
}
KINDS["unknown"] = KINDS["time"] | {"stem": "repeat_run_generic",
                                     "description": "Runs one pytest test repeatedly in fresh processes to measure its failure rate."}


@dataclass
class ToolSpec:
    stem: str
    description: str
    tags: list[str]


def spec_for(source: str) -> ToolSpec:
    k = KINDS.get(source, KINDS["unknown"])
    return ToolSpec(k["stem"], k["description"], list(k["tags"]))


def write_tool(source: str, tool_id: str, task_id: str, default_runs: int, llm: LLM | None = None) -> str:
    spec = KINDS.get(source, KINDS["unknown"])
    if llm is not None and llm.available:
        try:
            code = llm.complete(
                "You write small, safe, standard-library-only Python test harnesses. Output only the code.",
                f"Write a harness for this purpose: {spec['description']}\nContract: {CONTRACT}\n"
                f"Default runs: {default_runs}. Output a single python file, no markdown fences.",
                max_tokens=2000,
            ).strip()
        except LLMError as e:  # every provider down or rate-limited: the template still does the job
            log.warning("LLM tool writing failed, using the built-in template: %s", str(e)[:200])
        else:
            if code.startswith("```"):
                code = code.strip("`").split("\n", 1)[1]
            return code
    return _TEMPLATE.format(description=spec["description"], task_id=task_id, tool_id=tool_id,
                            default_runs=default_runs, loop_body=spec["loop_body"])
