"""Tools the Tester writes on the spot.

Every tool follows one contract so the Tester can run any of them the same way:

    python <tool>.py <pytest node id> <runs>
    -> prints one JSON line: {"test", "runs", "failures", "failure_rate", "failing": [...]}

With an LLM the Tester designs a harness for the failure in front of it: it reads the test, the code under
test and the coder's diagnosis, and writes a script that provokes that mechanism (a sweep of hash seeds for
set ordering, the test run after its neighbours for leaked state, a frozen or skewed clock, and so on), with
its own name, description and tags. Offline, or when a design doesn't hold up, it falls back to a template
matched to the kind of failure. Either way the tool is validated before it is trusted or saved.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

from .llm import LLM, LLMError

log = logging.getLogger("swarm.tester")

CONTRACT = (
    "A standalone Python 3 script. Usage: python tool.py <pytest node id> <runs>. It runs the test <runs> times "
    "in fresh subprocesses (sys.executable -m pytest -q -p no:cacheprovider <node id>) and prints exactly one JSON "
    'line: {"test": str, "runs": int, "failures": int, "failure_rate": float, "failing": [labels of failing runs]}. '
    "Standard library only, no network access."
)

_TEMPLATE = '''#!/usr/bin/env python3
"""{description}

Generated by the swarm's Tester agent for {task_id}.
Usage: python {tool_id}.py <pytest node id> [runs]
"""
import json
import os
import subprocess
import sys


def run_once(test, label, extra_env):
    env = dict(os.environ)
    env.update(extra_env)
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", test],
        env=env, capture_output=True, text=True, timeout=60,
    )
    return {{"label": label, "passed": proc.returncode == 0}}


def main():
    test = sys.argv[1]
    runs = int(sys.argv[2]) if len(sys.argv) > 2 else {default_runs}
    results = []
    for i in range(runs):
{loop_body}
    failing = [r["label"] for r in results if not r["passed"]]
    print(json.dumps({{
        "test": test, "runs": runs, "failures": len(failing),
        "failure_rate": round(len(failing) / runs, 3), "failing": failing,
    }}))


if __name__ == "__main__":
    main()
'''

KINDS = {
    "hash-order": dict(
        stem="hashseed_sweep",
        description="Runs one pytest test repeatedly under different PYTHONHASHSEED values to expose "
                    "random failures caused by set/dict iteration order (hash randomization).",
        tags=["flaky", "hash", "ordering", "set", "pythonhashseed", "repeat", "harness"],
        loop_body='        results.append(run_once(test, "PYTHONHASHSEED=%d" % i, {"PYTHONHASHSEED": str(i)}))',
    ),
    "rng": dict(
        stem="repeat_run",
        description="Runs one pytest test many times in fresh processes with unseeded randomness to measure "
                    "the failure rate of failures driven by randomness (RNG / jitter).",
        tags=["flaky", "random", "rng", "jitter", "repeat", "harness", "failure rate"],
        loop_body='        results.append(run_once(test, "run %d" % i, {"PYTHONHASHSEED": "random"}))',
    ),
    "time": dict(
        stem="timing_stress",
        description="Runs one pytest test repeatedly in fresh processes to measure timing-dependent random failures "
                    "(sleeps, clocks, timeouts).",
        tags=["flaky", "timing", "time", "sleep", "clock", "repeat", "harness"],
        loop_body='        results.append(run_once(test, "run %d" % i, {}))',
    ),
}
ORDER_TEMPLATE = '''#!/usr/bin/env python3
"""{description}

Generated by the swarm's Tester agent for {task_id}.
Usage: python {tool_id}.py <pytest node id> [runs]
"""
import json
import random
import re
import subprocess
import sys


def neighbours(test):
    path, _, name = test.partition("::")
    try:
        src = open(path).read()
    except OSError:
        return []
    return [path + "::" + n for n in re.findall(r"^def (test_\\w+)", src, re.M) if n != name]


def run_order(test, before):
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "-rf", *before, test],
        capture_output=True, text=True, timeout=60,
    )
    return ("FAILED " + test) not in proc.stdout and proc.returncode in (0, 1)


def main():
    test = sys.argv[1]
    runs = int(sys.argv[2]) if len(sys.argv) > 2 else {default_runs}
    others = neighbours(test)
    results = []
    for i in range(runs):
        rng = random.Random(i)
        before = rng.sample(others, rng.randint(0, len(others))) if others else []
        label = "after " + ", ".join(b.split("::")[-1] for b in before) if before else "alone"
        results.append({{"label": label, "passed": run_order(test, before)}})
    failing = [r["label"] for r in results if not r["passed"]]
    print(json.dumps({{
        "test": test, "runs": runs, "failures": len(failing),
        "failure_rate": round(len(failing) / runs, 3), "failing": failing,
    }}))


if __name__ == "__main__":
    main()
'''

KINDS["shared-state"] = dict(
    stem="order_shuffle",
    description="Runs one pytest test after random picks of the other tests in its file, in shuffled order, to expose "
                "state that leaks between tests (mutable defaults, module-level caches) and order-dependent failures.",
    tags=["order", "test order", "shuffle", "leak", "shared state", "mutable default", "isolation", "harness"],
    template=ORDER_TEMPLATE,
)
KINDS["unknown"] = KINDS["time"] | {"stem": "repeat_run_generic",
                                     "description": "Runs one pytest test repeatedly in fresh processes to measure its failure rate."}


@dataclass
class ToolSpec:
    stem: str
    description: str
    tags: list[str]


def spec_for(source: str) -> ToolSpec:
    k = KINDS.get(source, KINDS["unknown"])
    return ToolSpec(k["stem"], k["description"], list(k["tags"]))


def template_tool(source: str, tool_id: str, task_id: str, default_runs: int) -> str:
    """The built-in harness for this kind of failure."""
    spec = KINDS.get(source, KINDS["unknown"])
    if "template" in spec:
        return spec["template"].format(description=spec["description"], task_id=task_id, tool_id=tool_id,
                                       default_runs=default_runs)
    return _TEMPLATE.format(description=spec["description"], task_id=task_id, tool_id=tool_id,
                            default_runs=default_runs, loop_body=spec["loop_body"])


@dataclass
class ToolDesign:
    stem: str
    description: str
    tags: list[str] = field(default_factory=list)
    code: str = ""


DESIGN_SYSTEM = (
    "You are the Tester in a team of agents that fix tests which fail at random. You design small, focused test "
    "harnesses: standard-library Python scripts that make one specific intermittent failure show up reliably, so a "
    "fix can be proven rather than hoped for. Design for the mechanism in front of you (hash seeds for set or dict "
    "order, the test run after its neighbours for leaked state, a skewed TZ or clock for time, seeds or many runs for "
    "randomness, several runs at once for races). Only fall back to plain repetition when repetition really is what "
    "exposes it. Never edit the repository's files; change the conditions a run happens under (environment "
    "variables, test order, arguments, parallel processes)."
)
FORMAT = (
    "Answer in exactly this shape, nothing before or after:\n"
    "NAME: <snake_case name for the technique, 2-4 words, no version number>\n"
    "DESCRIPTION: <one or two sentences: what the harness varies and which kind of failure it exposes, written so "
    "another agent can tell whether it fits their failure>\n"
    "TAGS: <5-8 short comma-separated keywords>\n"
    "---\n"
    "<the python script, no markdown fences>"
)


def design_tool(context: str, default_runs: int, llm: LLM, feedback: str = "") -> ToolDesign | None:
    """Ask the LLM for a harness built for this failure. None when no provider answers or the answer isn't usable."""
    prompt = (f"{context}\n\nContract: {CONTRACT} Each run in a fresh subprocess with a timeout of at most 60 seconds; "
              f"label every run with the condition it ran under (e.g. \"PYTHONHASHSEED=7\" or \"after test_a, test_b\"). "
              f"Default runs: {default_runs}.\n")
    if feedback:
        prompt += f"\nYour previous harness didn't hold up: {feedback}\nDesign a better one.\n"
    try:
        text = llm.complete(DESIGN_SYSTEM, prompt + "\n" + FORMAT, max_tokens=3000)
    except LLMError as e:  # every provider down or rate-limited: the template still does the job
        log.warning("LLM tool design failed, using the built-in template: %s", str(e)[:200])
        return None
    return parse_design(text)


def parse_design(text: str) -> ToolDesign | None:
    head, sep, code = text.strip().partition("\n---")
    if not sep:
        return None
    code = code.lstrip("-").strip()
    fenced = re.search(r"```(?:python)?\s*\n(.*?)```", code, re.S)
    if fenced:
        code = fenced.group(1)
    fields = {k.lower(): v.strip() for k, v in re.findall(r"^\s*(NAME|DESCRIPTION|TAGS)\s*:\s*(.+)$", head, re.M | re.I)}
    stem = re.sub(r"_v\d+$", "", re.sub(r"[^a-z0-9]+", "_", fields.get("name", "").lower()).strip("_"))[:40]
    description = fields.get("description", "")[:400]
    tags = [t.strip().lower()[:30] for t in fields.get("tags", "").split(",") if t.strip()][:8]
    if not stem or not description or "json" not in code:
        return None
    try:
        compile(code, f"{stem}.py", "exec")
    except SyntaxError:
        return None
    return ToolDesign(stem, description, tags, code.strip() + "\n")
